Fix compatibility with rubytest 0.5+
Since rubytest 0.5, `Test::Runner.cli` gets removed, which breaks the
lemons command line utility:

```
lib/lemon/cli.rb:28:in `cli': undefined method `cli' for
Test::Runner:Class (NoMethodError)
```

As the CLI functionality was split off as `rubytest-cli`, let's depend
on it instead and adapt to the new method name.

Since the original test folder is no longer present now with lemon 0.9+,
I can at least verify that lemons runs successfully with rubytest 0.7.0
+ rubytest-cli 0.1.0 after this change.